# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Latest release

env:
  CACHE_VERSION: 21
  DEFAULT_PYTHON: "3.13"

# Only run on merges
on:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  publishing:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    # Only trigger on merges, not just closes
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out committed code
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Prepare uv
        run: |
          pip install uv
          uv venv --seed venv
      - name: Build
        run: |
          . venv/bin/activate
          uv build
      - name: Publish distribution 📦 to PyPI
        run: |
          . venv/bin/activate
          uv publish
